export default {
  Backquote: {
    code: 'Backquote',
    ru: ']',
    shiftedRu: '[',
    capsRu: ']',
    capsAndShiftRu: '[',
    en: '`',
    shiftedEn: '~',
    capsEn: '`',
    capsAndShiftEn: '~',

  },
  Digit1: {
    code: 'Digit1',
    ru: '1',
    shiftedRu: '!',
    capsRu: '1',
    capsAndShiftRu: '!',
    en: '1',
    shiftedEn: '!',
    capsEn: '1',
    capsAndShiftEn: '!',
  },
  Digit2: {
    code: 'Digit2',
    ru: '2',
    shiftedRu: '"',
    capsRu: '2',
    capsAndShiftRu: '"',
    en: '2',
    shiftedEn: '@',
    capsEn: '2',
    capsAndShiftEn: '@',
  },
  Digit3: {
    code: 'Digit3',
    ru: '3',
    shiftedRu: '№',
    capsRu: '3',
    capsAndShiftRu: '№',
    en: '3',
    shiftedEn: '#',
    capsEn: '3',
    capsAndShiftEn: '#',
  },
  Digit4: {
    code: 'Digit4',
    ru: '4',
    shiftedRu: '%',
    capsRu: '4',
    capsAndShiftRu: '%',
    en: '4',
    shiftedEn: '$',
    capsEn: '4',
    capsAndShiftEn: '$',
  },
  Digit5: {
    code: 'Digit5',
    ru: '5',
    shiftedRu: ':',
    capsRu: '5',
    capsAndShiftRu: ':',
    en: '5',
    shiftedEn: '%',
    capsEn: '5',
    capsAndShiftEn: '%',
  },
  Digit6: {
    code: 'Digit6',
    ru: '6',
    shiftedRu: ',',
    capsRu: '6',
    capsAndShiftRu: ',',
    en: '6',
    shiftedEn: '^',
    capsEn: '6',
    capsAndShiftEn: '^',
  },
  Digit7: {
    code: 'Digit7',
    ru: '7',
    shiftedRu: '.',
    capsRu: '7',
    capsAndShiftRu: '.',
    en: '7',
    shiftedEn: '&',
    capsEn: '7',
    capsAndShiftEn: '&',
  },
  Digit8: {
    code: 'Digit8',
    ru: '8',
    shiftedRu: ';',
    capsRu: '8',
    capsAndShiftRu: ';',
    en: '8',
    shiftedEn: '*',
    capsEn: '8',
    capsAndShiftEn: '*',
  },
  Digit9: {
    code: 'Digit9',
    ru: '9',
    shiftedRu: '(',
    capsRu: '9',
    capsAndShiftRu: '(',
    en: '9',
    shiftedEn: '(',
    capsEn: '9',
    capsAndShiftEn: '(',
  },
  Digit0: {
    code: 'Digit9',
    ru: '0',
    shiftedRu: ')',
    capsRu: '0',
    capsAndShiftRu: ')',
    en: '0',
    shiftedEn: ')',
    capsEn: '0',
    capsAndShiftEn: ')',
  },
  Minus: {
    code: 'Minus',
    ru: '-',
    shiftedRu: '_',
    capsRu: '-',
    capsAndShiftRu: '_',
    en: '-',
    shiftedEn: '_',
    capsEn: '-',
    capsAndShiftEn: '_',
  },
  Equal: {
    code: 'Equal',
    ru: '=',
    shiftedRu: '+',
    capsRu: '=',
    capsAndShiftRu: '+',
    en: '=',
    shiftedEn: '+',
    capsEn: '=',
    capsAndShiftEn: '+',
  },
  Backspace: {
    code: 'Backspace',
    ru: 'Backspace',
    shiftedRu: 'Backspace',
    capsRu: 'Backspace',
    capsAndShiftRu: 'Backspace',
    en: 'Backspace',
    shiftedEn: 'Backspace',
    capsEn: 'Backspace',
    capsAndShiftEn: 'Backspace',
  },
  Tab: {
    code: 'Tab',
    ru: 'Tab',
    shiftedRu: 'Tab',
    capsRu: 'Tab',
    capsAndShiftRu: 'Tab',
    en: 'Tab',
    shiftedEn: 'Tab',
    capsEn: 'Tab',
    capsAndShiftEn: 'Tab',
  },
  KeyQ: {
    code: 'KeyQ',
    ru: 'й',
    shiftedRu: 'Й',
    capsRu: 'Й',
    capsAndShiftRu: 'й',
    en: 'q',
    shiftedEn: 'Q',
    capsEn: 'Q',
    capsAndShiftEn: 'q',
  },
  KeyW: {
    code: 'KeyW',
    ru: 'ц',
    shiftedRu: 'Ц',
    capsRu: 'Ц',
    capsAndShiftRu: 'ц',
    en: 'w',
    shiftedEn: 'W',
    capsEn: 'W',
    capsAndShiftEn: 'w',
  },
  KeyE: {
    code: 'KeyE',
    ru: 'у',
    shiftedRu: 'У',
    capsRu: 'У',
    capsAndShiftRu: 'У',
    en: 'e',
    shiftedEn: 'E',
    capsEn: 'E',
    capsAndShiftEn: 'e',
  },
  KeyR: {
    code: 'KeyR',
    ru: 'к',
    shiftedRu: 'К',
    capsRu: 'К',
    capsAndShiftRu: 'к',
    en: 'r',
    shiftedEn: 'R',
    capsEn: 'R',
    capsAndShiftEn: 'r',
  },
  KeyT: {
    code: 'KeyT',
    ru: 'е',
    shiftedRu: 'Е',
    capsRu: 'Е',
    capsAndShiftRu: 'е',
    en: 't',
    shiftedEn: 'T',
    capsEn: 'T',
    capsAndShiftEn: 't',
  },
  KeyY: {
    code: 'KeyY',
    ru: 'н',
    shiftedRu: 'Н',
    capsRu: 'Н',
    capsAndShiftRu: 'н',
    en: 'y',
    shiftedEn: 'Y',
    capsEn: 'Y',
    capsAndShiftEn: 'y',
  },
  KeyU: {
    code: 'KeyU',
    ru: 'г',
    shiftedRu: 'Г',
    capsRu: 'Г',
    capsAndShiftRu: 'г',
    en: 'u',
    shiftedEn: 'U',
    capsEn: 'U',
    capsAndShiftEn: 'u',
  },
  KeyI: {
    code: 'KeyI',
    ru: 'ш',
    shiftedRu: 'Ш',
    capsRu: 'Ш',
    capsAndShiftRu: 'ш',
    en: 'i',
    shiftedEn: 'I',
    capsEn: 'I',
    capsAndShiftEn: 'i',
  },
  KeyO: {
    code: 'KeyO',
    ru: 'щ',
    shiftedRu: 'Щ',
    capsRu: 'Щ',
    capsAndShiftRu: 'щ',
    en: 'o',
    shiftedEn: 'O',
    capsEn: 'O',
    capsAndShiftEn: 'o',
  },
  KeyP: {
    code: 'KeyP',
    ru: 'з',
    shiftedRu: 'З',
    capsRu: 'З',
    capsAndShiftRu: 'з',
    en: 'p',
    shiftedEn: 'P',
    capsEn: 'P',
    capsAndShiftEn: 'p',
  },
  BracketLeft: {
    code: 'BracketLeft',
    ru: 'х',
    shiftedRu: 'Х',
    capsRu: 'Х',
    capsAndShiftRu: 'х',
    en: '[',
    shiftedEn: '{',
    capsEn: '[',
    capsAndShiftEn: '{',
  },
  BracketRight: {
    code: 'BracketRight',
    ru: 'ъ',
    shiftedRu: 'Ъ',
    capsRu: 'Ъ',
    capsAndShiftRu: 'ъ',
    en: ']',
    shiftedEn: '}',
    capsEn: ' ]',
    capsAndShiftEn: '}',
  },
  Backslash: {
    code: 'Backslash',
    ru: 'ё',
    shiftedRu: 'Ё',
    capsRu: 'Ё',
    capsAndShiftRu: 'ё',
    en: '\\',
    shiftedEn: '|',
    capsEn: '\\',
    capsAndShiftEn: '|',
  },
  CapsLock: {
    code: 'CapsLock',
    ru: 'caps lock',
    shiftedRu: 'caps lock',
    capsRu: 'caps lock',
    capsAndShiftRu: 'caps lock',
    en: 'caps lock',
    shiftedEn: 'caps lock',
    capsEn: 'caps lock',
    capsAndShiftEn: 'caps lock',
  },
  KeyA: {
    code: 'KeyA',
    ru: 'ф',
    shiftedRu: 'Ф',
    capsRu: 'Ф',
    capsAndShiftRu: 'ф',
    en: 'a',
    shiftedEn: 'A',
    capsEn: 'A',
    capsAndShiftEn: 'a',
  },
  KeyS: {
    code: 'KeyS',
    ru: 'ы',
    shiftedRu: 'Ы',
    capsRu: 'Ы',
    capsAndShiftRu: 'ы',
    en: 's',
    shiftedEn: 'S',
    capsEn: 'S',
    capsAndShiftEn: 's',
  },
  KeyD: {
    code: 'KeyD',
    ru: 'в',
    shiftedRu: 'В',
    capsRu: 'В',
    capsAndShiftRu: 'в',
    en: 'd',
    shiftedEn: 'D',
    capsEn: 'D',
    capsAndShiftEn: 'd',
  },
  KeyF: {
    code: 'KeyF',
    ru: 'а',
    shiftedRu: 'А',
    capsRu: 'А',
    capsAndShiftRu: 'а',
    en: 'f',
    shiftedEn: 'F',
    capsEn: 'F',
    capsAndShiftEn: 'f',
  },
  KeyG: {
    code: 'KeyG',
    ru: 'п',
    shiftedRu: 'П',
    capsRu: 'П',
    capsAndShiftRu: 'п',
    en: 'g',
    shiftedEn: 'G',
    capsEn: 'G',
    capsAndShiftEn: 'g',
  },
  KeyH: {
    code: 'KeyH',
    ru: 'р',
    shiftedRu: 'Р',
    capsRu: 'Р',
    capsAndShiftRu: 'р',
    en: 'h',
    shiftedEn: 'H',
    capsEn: 'H',
    capsAndShiftEn: 'h',
  },
  KeyJ: {
    code: 'KeyJ',
    ru: 'о',
    shiftedRu: 'О',
    capsRu: 'О',
    capsAndShiftRu: 'о',
    en: 'j',
    shiftedEn: 'J',
    capsEn: 'J',
    capsAndShiftEn: 'j',
  },
  KeyK: {
    code: 'KeyK',
    ru: 'л',
    shiftedRu: 'Л',
    capsRu: 'Л',
    capsAndShiftRu: 'л',
    en: 'k',
    shiftedEn: 'K',
    capsEn: 'K',
    capsAndShiftEn: 'k',
  },
  KeyL: {
    code: 'KeyL',
    ru: 'д',
    shiftedRu: 'Д',
    capsRu: 'Д',
    capsAndShiftRu: 'д',
    en: 'l',
    shiftedEn: 'L',
    capsEn: 'L',
    capsAndShiftEn: 'l',
  },
  Semicolon: {
    code: 'Semicolon',
    ru: 'ж',
    shiftedRu: 'Ж',
    capsRu: 'Ж',
    capsAndShiftRu: 'ж',
    en: ';',
    shiftedEn: ':',
    capsEn: ';',
    capsAndShiftEn: ':',
  },
  Quote: {
    code: 'Quote',
    ru: 'э',
    shiftedRu: 'Э',
    capsRu: 'Э',
    capsAndShiftRu: 'э',
    en: '\'',
    shiftedEn: '"',
    capsEn: '\'',
    capsAndShiftEn: '"',
  },
  Enter: {
    code: 'Enter',
    ru: 'return',
    shiftedRu: 'return',
    capsRu: 'return',
    capsAndShiftRu: 'return',
    en: 'return',
    shiftedEn: 'return',
    capsEn: 'return',
    capsAndShiftEn: 'return',
  },
  ShiftLeft: {
    code: 'ShiftLeft',
    ru: 'shift',
    shiftedRu: 'shift',
    capsRu: 'shift',
    capsAndShiftRu: 'shift',
    en: 'shift',
    shiftedEn: 'shift',
    capsEn: 'shift',
    capsAndShiftEn: 'shift',
  },
  KeyZ: {
    code: 'KeyZ',
    ru: 'я',
    shiftedRu: 'Я',
    capsRu: 'Я',
    capsAndShiftRu: 'я',
    en: 'z',
    shiftedEn: 'Z',
    capsEn: 'Z',
    capsAndShiftEn: 'z',
  },
  KeyX: {
    code: 'KeyX',
    ru: 'ч',
    shiftedRu: 'Ч',
    capsRu: 'Ч',
    capsAndShiftRu: 'ч',
    en: 'x',
    shiftedEn: 'X',
    capsEn: 'X',
    capsAndShiftEn: 'x',
  },
  KeyC: {
    code: 'KeyC',
    ru: 'с',
    shiftedRu: 'С',
    capsRu: 'С',
    capsAndShiftRu: 'с',
    en: 'c',
    shiftedEn: 'C',
    capsEn: 'C',
    capsAndShiftEn: 'c',
  },
  KeyV: {
    code: 'KeyV',
    ru: 'м',
    shiftedRu: 'М',
    capsRu: 'М',
    capsAndShiftRu: 'м',
    en: 'v',
    shiftedEn: 'V',
    capsEn: 'V',
    capsAndShiftEn: 'v',
  },
  KeyB: {
    code: 'KeyB',
    ru: 'и',
    shiftedRu: 'И',
    capsRu: 'И',
    capsAndShiftRu: 'и',
    en: 'b',
    shiftedEn: 'B',
    capsEn: 'B',
    capsAndShiftEn: 'b',
  },
  KeyN: {
    code: 'KeyN',
    ru: 'т',
    shiftedRu: 'Т',
    capsRu: 'Т',
    capsAndShiftRu: 'т',
    en: 'n',
    shiftedEn: 'N',
    capsEn: 'N',
    capsAndShiftEn: 'n',
  },
  KeyM: {
    code: 'KeyM',
    ru: 'ь',
    shiftedRu: 'Ь',
    capsRu: 'Ь',
    capsAndShiftRu: 'ь',
    en: 'm',
    shiftedEn: 'M',
    capsEn: 'M',
    capsAndShiftEn: 'm',
  },
  Comma: {
    code: 'Comma',
    ru: 'б',
    shiftedRu: 'Б',
    capsRu: 'Б',
    capsAndShiftRu: 'б',
    en: ',',
    shiftedEn: '<',
    capsEn: ',',
    capsAndShiftEn: '<',
  },
  Period: {
    code: 'Period',
    ru: 'ю',
    shiftedRu: 'Ю',
    capsRu: 'Ю',
    capsAndShiftRu: 'ю',
    en: '.',
    shiftedEn: '>',
    capsEn: '.',
    capsAndShiftEn: '>',
  },
  Slash: {
    code: 'Slash',
    ru: '/',
    shiftedRu: '?',
    capsRu: '/',
    capsAndShiftRu: '?',
    en: '/',
    shiftedEn: '?',
    capsEn: '/',
    capsAndShiftEn: '?',
  },
  ShiftRight: {
    code: 'ShiftRight',
    ru: 'shift',
    shiftedRu: 'shift',
    capsRu: 'shift',
    capsAndShiftRu: 'shift',
    en: 'shift',
    shiftedEn: 'shift',
    capsEn: 'shift',
    capsAndShiftEn: 'shift',
  },
  ControlLeft: {
    code: 'ControlLeft',
    ru: 'control',
    shiftedRu: 'control',
    capsRu: 'control',
    capsAndShiftRu: 'control',
    en: 'control',
    shiftedEn: 'control',
    capsEn: 'control',
    capsAndShiftEn: 'control',
  },
  AltLeft: {
    code: 'AltLeft',
    ru: 'option',
    shiftedRu: 'option',
    capsRu: 'option',
    capsAndShiftRu: 'option',
    en: 'option',
    shiftedEn: 'option',
    capsEn: 'option',
    capsAndShiftEn: 'option',
  },
  MetaLeft: {
    code: 'MetaLeft',
    ru: 'command',
    shiftedRu: 'command',
    capsRu: 'command',
    capsAndShiftRu: 'command',
    en: 'command',
    shiftedEn: 'command',
    capsEn: 'command',
    capsAndShiftEn: 'command',
  },
  Space: {
    code: 'Space',
    ru: 'space',
    shiftedRu: 'space',
    capsRu: 'space',
    capsAndShiftRu: 'space',
    en: 'space',
    shiftedEn: 'space',
    capsEn: 'space',
    capsAndShiftEn: 'space',
  },
  MetaRight: {
    code: 'MetaRight',
    ru: 'command',
    shiftedRu: 'command',
    capsRu: 'command',
    capsAndShiftRu: 'command',
    en: 'command',
    shiftedEn: 'command',
    capsEn: 'command',
    capsAndShiftEn: 'command',
  },
  AltRight: {
    code: 'AltRight',
    ru: 'option',
    shiftedRu: 'option',
    capsRu: 'option',
    capsAndShiftRu: 'option',
    en: 'option',
    shiftedEn: 'option',
    capsEn: 'option',
    capsAndShiftEn: 'option',
  },
  ArrowLeft: {
    code: 'ArrowLeft',
    ru: '◀',
    shiftedRu: '◀',
    capsRu: '◀',
    capsAndShiftRu: '◀',
    en: '◀',
    shiftedEn: '◀',
    capsEn: '◀',
    capsAndShiftEn: '◀',
  },
  ArrowUp: {
    code: 'ArrowUp',
    ru: '▲',
    shiftedRu: '▲',
    capsRu: '▲',
    capsAndShiftRu: '▲',
    en: '▲',
    shiftedEn: '▲',
    capsEn: '▲',
    capsAndShiftEn: '▲',
  },
  ArrowDown: {
    code: 'ArrowDown',
    ru: '▼',
    shiftedRu: '▼',
    capsRu: '▼',
    capsAndShiftRu: '▼',
    en: '▼',
    shiftedEn: '▼',
    capsEn: '▼',
    capsAndShiftEn: '▼',
  },
  ArrowRight: {
    code: 'ArrowRight',
    ru: '►',
    shiftedRu: '►',
    capsRu: '►',
    capsAndShiftRu: '►',
    en: '►',
    shiftedEn: '►',
    capsEn: '►',
    capsAndShiftEn: '►',
  },
};
