export default {
  Backquote: {
    code: 'Backquote',
    ru: ']',
    shiftedRu: '[',
    en: '`',
    shiftedEn: '~',
  },
  Digit1: {
    code: 'Digit1',
    ru: '1',
    shiftedRu: '!',
    en: '1',
    shiftedEn: '!',
  },
  Digit2: {
    code: 'Digit2',
    ru: '2',
    shiftedRu: '"',
    en: '2',
    shiftedEn: '@',
  },
  Digit3: {
    code: 'Digit3',
    ru: '3',
    shiftedRu: '№',
    en: '3',
    shiftedEn: '#',
  },
  Digit4: {
    code: 'Digit4',
    ru: '4',
    shiftedRu: '%',
    en: '4',
    shiftedEn: '$',
  },
  Digit5: {
    code: 'Digit5',
    ru: '5',
    shiftedRu: ':',
    en: '5',
    shiftedEn: ':%',
  },
  Digit6: {
    code: 'Digit6',
    ru: '6',
    shiftedRu: ',',
    en: '6',
    shiftedEn: '^',
  },
  Digit7: {
    code: 'Digit7',
    ru: '7',
    shiftedRu: '.',
    en: '7',
    shiftedEn: '&',
  },
  Digit8: {
    code: 'Digit8',
    ru: '8',
    shiftedRu: ';',
    en: '8',
    shiftedEn: '*',
  },
  Digit9: {
    code: 'Digit9',
    ru: '9',
    shiftedRu: '(',
    en: '9',
    shiftedEn: '(',
  },
  Digit0: {
    code: 'Digit9',
    ru: '0',
    shiftedRu: ')',
    en: '0',
    shiftedEn: ')',
  },
  Minus: {
    code: 'Minus',
    ru: '-',
    shiftedRu: '_',
    en: '-',
    shiftedEn: '_',
  },
  Equal: {
    code: 'Equal',
    ru: '=',
    shiftedRu: '+',
    en: '=',
    shiftedEn: '+',
  },
  Backspace: {
    code: 'Backspace',
    ru: 'Backspace',
    shiftedRu: 'Backspace',
    en: 'Backspace',
    shiftedEn: 'Backspace',
  },
  Tab: {
    code: 'Tab',
    ru: 'Tab',
    shiftedRu: 'Tab',
    en: 'Tab',
    shiftedEn: 'Tab',
  },
  KeyQ: {
    code: 'KeyQ',
    ru: 'й',
    shiftedRu: 'Й',
    en: 'q',
    shiftedEn: 'Q',
  },
  KeyW: {
    code: 'KeyW',
    ru: 'ц',
    shiftedRu: 'Ц',
    en: 'w',
    shiftedEn: 'W',
  },
  KeyE: {
    code: 'KeyE',
    ru: 'у',
    shiftedRu: 'У',
    en: 'e',
    shiftedEn: 'E',
  },
  KeyR: {
    code: 'KeyR',
    ru: 'к',
    shiftedRu: 'К',
    en: 'r',
    shiftedEn: 'R',
  },
  KeyT: {
    code: 'KeyT',
    ru: 'е',
    shiftedRu: 'Е',
    en: 't',
    shiftedEn: 'T',
  },
  KeyY: {
    code: 'KeyY',
    ru: 'Н',
    shiftedRu: 'Н',
    en: 'y',
    shiftedEn: 'Y',
  },
  KeyU: {
    code: 'KeyU',
    ru: 'г',
    shiftedRu: 'Г',
    en: 'u',
    shiftedEn: 'U',
  },
  KeyI: {
    code: 'KeyI',
    ru: 'ш',
    shiftedRu: 'Ш',
    en: 'i',
    shiftedEn: 'I',
  },
  KeyO: {
    code: 'KeyO',
    ru: 'щ',
    shiftedRu: 'Щ',
    en: 'o',
    shiftedEn: 'O',
  },
  KeyP: {
    code: 'KeyP',
    ru: 'з',
    shiftedRu: 'З',
    en: 'p',
    shiftedEn: 'P',
  },
  BracketLeft: {
    code: 'BracketLeft',
    ru: 'х',
    shiftedRu: 'Х',
    en: '[',
    shiftedEn: '{',
  },
  BracketRight: {
    code: 'BracketRight',
    ru: 'ъ',
    shiftedRu: 'Ъ',
    en: ']',
    shiftedEn: '}',
  },
  Backslash: {
    code: 'Backslash',
    ru: 'ё',
    shiftedRu: 'Ё',
    en: '\\',
    shiftedEn: '|',
  },
  CapsLock: {
    code: 'CapsLock',
    ru: 'caps lock',
    shiftedRu: 'caps lock',
    en: 'caps lock',
    shiftedEn: 'caps lock',
  },
  KeyA: {
    code: 'KeyA',
    ru: 'ф',
    shiftedRu: 'Ф',
    en: 'a',
    shiftedEn: 'A',
  },
  KeyS: {
    code: 'KeyS',
    ru: 'ы',
    shiftedRu: 'Ы',
    en: 's',
    shiftedEn: 'S',
  },
  KeyD: {
    code: 'KeyD',
    ru: 'в',
    shiftedRu: 'В',
    en: 'd',
    shiftedEn: 'D',
  },
  KeyF: {
    code: 'KeyF',
    ru: 'а',
    shiftedRu: 'А',
    en: 'f',
    shiftedEn: 'F',
  },
  KeyG: {
    code: 'KeyG',
    ru: 'п',
    shiftedRu: 'П',
    en: 'g',
    shiftedEn: 'G',
  },
  KeyH: {
    code: 'KeyH',
    ru: 'р',
    shiftedRu: 'Р',
    en: 'h',
    shiftedEn: 'H',
  },
  KeyJ: {
    code: 'KeyJ',
    ru: 'о',
    shiftedRu: 'О',
    en: 'j',
    shiftedEn: 'J',
  },
  KeyK: {
    code: 'KeyK',
    ru: 'л',
    shiftedRu: 'Л',
    en: 'k',
    shiftedEn: 'K',
  },
  KeyL: {
    code: 'KeyL',
    ru: 'д',
    shiftedRu: 'Д',
    en: 'l',
    shiftedEn: 'L',
  },
  Semicolon: {
    code: 'Semicolon',
    ru: 'ж',
    shiftedRu: 'Ж',
    en: ';',
    shiftedEn: ':',
  },
  Quote: {
    code: 'Quote',
    ru: 'э',
    shiftedRu: 'Э',
    en: '\'',
    shiftedEn: '"',
  },
  Enter: {
    code: 'Enter',
    ru: 'return',
    shiftedRu: 'return',
    en: 'return',
    shiftedEn: 'return',
  },
  ShiftLeft: {
    code: 'ShiftLeft',
    ru: 'shift',
    shiftedRu: 'shift',
    en: 'shift',
    shiftedEn: 'shift',
  },
  KeyZ: {
    code: 'KeyZ',
    ru: 'я',
    shiftedRu: 'Я',
    en: 'z',
    shiftedEn: 'Z',
  },
  KeyX: {
    code: 'KeyX',
    ru: 'ч',
    shiftedRu: 'Ч',
    en: 'x',
    shiftedEn: 'X',
  },
  KeyC: {
    code: 'KeyC',
    ru: 'с',
    shiftedRu: 'С',
    en: 'c',
    shiftedEn: 'C',
  },
  KeyV: {
    code: 'KeyV',
    ru: 'м',
    shiftedRu: 'М',
    en: 'v',
    shiftedEn: 'V',
  },
  KeyB: {
    code: 'KeyB',
    ru: 'и',
    shiftedRu: 'И',
    en: 'b',
    shiftedEn: 'B',
  },
  KeyN: {
    code: 'KeyN',
    ru: 'т',
    shiftedRu: 'Т',
    en: 'n',
    shiftedEn: 'N',
  },
  KeyM: {
    code: 'KeyM',
    ru: 'ь',
    shiftedRu: 'Ь',
    en: 'm',
    shiftedEn: 'M',
  },
  Comma: {
    code: 'Comma',
    ru: 'б',
    shiftedRu: 'Б',
    en: ',',
    shiftedEn: '<',
  },
  Period: {
    code: 'Period',
    ru: 'ю',
    shiftedRu: 'Ю',
    en: '.',
    shiftedEn: '>',
  },
  Slash: {
    code: 'Slash',
    ru: '/',
    shiftedRu: '?',
    en: '/',
    shiftedEn: '?',
  },
  ShiftRight: {
    code: 'ShiftRight',
    ru: 'shift',
    shiftedRu: 'shift',
    en: 'shift',
    shiftedEn: 'shift',
  },
  ControlLeft: {
    code: 'ControlLeft',
    ru: 'control',
    shiftedRu: 'control',
    en: 'control',
    shiftedEn: 'control',
  },
  AltLeft: {
    code: 'AltLeft',
    ru: 'option',
    shiftedRu: 'option',
    en: 'option',
    shiftedEn: 'option',
  },
  MetaLeft: {
    code: 'MetaLeft',
    ru: 'command',
    shiftedRu: 'command',
    en: 'command',
    shiftedEn: 'command',
  },
  Space: {
    code: 'Space',
    ru: 'space',
    shiftedRu: 'space',
    en: 'space',
    shiftedEn: 'space',
  },
  MetaRight: {
    code: 'MetaRight',
    ru: 'command',
    shiftedRu: 'command',
    en: 'command',
    shiftedEn: 'command',
  },
  AltRight: {
    code: 'AltRight',
    ru: 'option',
    shiftedRu: 'option',
    en: 'option',
    shiftedEn: 'option',
  },
  ArrowLeft: {
    code: 'ArrowLeft',
    ru: '&larr',
    shiftedRu: '&larr',
    en: '&larr',
    shiftedEn: '&larr',
  },
  ArrowUp: {
    code: 'ArrowUp',
    ru: '&uarr',
    shiftedRu: '&uarr',
    en: '&uarr',
    shiftedEn: '&uarr',
  },
  ArrowDown: {
    code: 'ArrowDown',
    ru: '&rarr',
    shiftedRu: '&rarr',
    en: '&rarr',
    shiftedEn: '&rarr',
  },
  ArrowRight: {
    code: 'ArrowRight',
    ru: '&darr',
    shiftedRu: '&darr',
    en: '&darr',
    shiftedEn: '&darr',
  },
};
